resources:
- name: concourse-test-am
  type: git
  icon: github
  source:
    uri: https://github.com/andreasmihm/concourse-test.git

jobs:
- name: read-the-readme
  plan:
  - get: concourse-test-am
    trigger: true
  - task: cat-readme
    file: concourse-test-am/cat-readme.yml
    #concourse-test-am: concourse-test-am
#    config:
#      platform: linux
#      image_resource:
#        type: registry-image
#       source:
#          repository: busybox
#      inputs: # pass concourse-examples into this task step
#      - name: concourse-test-am
#      run:
#        path: cat
#        args: ["concourse-test-am/pipeline.yml"]