resources:
- name: concourse-test-am
  type: git
  icon: github
  source:
    uri: https://github.com/andreasmihm/concourse-test.git

jobs:
- name: read-the-readme
  plan:
  - get: oncourse-test-am
  - task: cat-readme
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: busybox
      inputs: # pass concourse-examples into this task step
      - name: oncourse-test-am
      run:
        path: cat
        args: ["oncourse-test-am/README.md"]